# Generated by Django 4.1.7 on 2023-03-06 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_doctor_alter_customer_options_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pass_text',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_summary', models.TextField()),
                ('days_spent', models.IntegerField(blank=True, null=True)),
                ('billing_date', models.DateField()),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='account.patient')),
            ],
        ),
    ]
