# Generated by Django 4.1.7 on 2023-03-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_patient_pass_text_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='report_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
