# Generated by Django 4.1.7 on 2023-03-07 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_billing_report_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_name', models.CharField(blank=True, max_length=150, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_value', models.CharField(blank=True, max_length=30, null=True)),
                ('bill_qty', models.CharField(default=0, max_length=30)),
                ('billing_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_item', to='account.billingspecification')),
            ],
        ),
    ]
