# Generated by Django 4.1.7 on 2023-03-07 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_billing_options_billingitem_billing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitem',
            name='billing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_items', to='account.billing'),
        ),
    ]
