# Generated by Django 4.1.7 on 2023-03-07 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_billingitem_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitem',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_items', to='account.billing'),
        ),
    ]
