# Generated by Django 4.1.7 on 2023-03-07 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_billingitem_billing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.patient'),
        ),
    ]
