# Generated by Django 4.1.7 on 2023-03-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='account.billing'),
        ),
    ]
