# Generated by Django 4.1.7 on 2023-03-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_payment_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
