# Generated by Django 4.1.7 on 2023-03-09 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_payment_payment_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApointMent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='account.patient')),
            ],
        ),
    ]
