# Generated by Django 4.1.7 on 2023-03-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_apointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='picture',
            field=models.ImageField(default='default-img.jpg', upload_to='patient_pictures'),
        ),
    ]
