# Generated by Django 4.1.7 on 2023-03-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_remove_billing_balance_billing_billing_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='currency',
            field=models.CharField(default='$', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='picture',
            field=models.FileField(default='default-img.jpg', upload_to='patient_pictures'),
        ),
    ]
