# Generated by Django 4.1.7 on 2023-03-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_billing_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='currency',
            field=models.CharField(choices=[('$', 'USD'), ('£', 'Pounds'), ('€', 'Euro')], max_length=10),
        ),
    ]
